apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: py-app
  template:
    metadata:
      labels:
        app: py-app
    spec:
      containers:
        - name: py-app
          image: shadrach85/py_flash:latest
          ports:
            - containerPort: 5000

