name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r py_flash/requirements.txt

    - name: Build Docker image
      run: docker build -t py-pipetest:${{github.sha}} -f py_flash/Dockerfile .

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.SECRET_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Docker image
      run: |
        docker tag py-pipetest:${{github.sha}} ${{ secrets.SECRET_USERNAME }}/py-pipetest:${{github.sha}}
        docker tag py-pipetest:${{github.sha}} ${{ secrets.SECRET_USERNAME }}/py-pipetest:latest

    - name: Push Docker image
      run: |
        docker push ${{ secrets.SECRET_USERNAME }}/py-pipetest:${{github.sha}}
        docker push ${{ secrets.SECRET_USERNAME }}/py-pipetest:latest
    
    - name: Install Snyk CLI
      run: |
         curl -sL https://github.com/snyk/snyk/releases/latest/download/snyk-linux -o snyk
         chmod +x snyk
         echo "$HOME/snyk" >> $GITHUB_PATH
         echo $PATH
    
    - name: Snyk Scan
      run: snyk container test ${{ secrets.SECRET_USERNAME }}/py_flash:${{github.sha}}

    - name: Post Snyk Results
      run: snyk monitor ${{ secrets.SECRET_USERNAME }}/py_flash:${{github.sha}}
